version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-proxy"
        versions: ">= 10.0"
    open-pull-requests-limit: 10
