version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-proxy"
        versions: ">= 10.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.transport.ecf"
        versions: ">= 1.3.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.repository"
        versions: ">= 2.5.0"
    open-pull-requests-limit: 10
