version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.transport.ecf"
        versions: ">= 1.3.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.repository"
        versions: ">= 2.5.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.debug.core"
        versions: ">= 3.17.0"
      - dependency-name: "org.eclipse.jdt:org.eclipse.jdt.launching"
        versions: ">= 3.18.0"
      - dependency-name: "org.eclipse.pde:org.eclipse.pde.core"
        versions: ">= 3.14.0"
    open-pull-requests-limit: 10
